#!/bin/sh
# Currently, we only dispatch according to command.  However, a more
# elaborate system might dispatch by command and interface or do some
# common initialization first, especially if more dhcp event notifications
# are added.
action=$1

echo DHCP todo action $action
if [ $action = "NAK" -o $action = "renew" ]
then
    action=bound
fi    
echo DHCP action $action
exec /usr/share/udhcpc/default.$action
