#!/bin/sh

rm -rf /mnt/sd1
mkdir  /mnt/sd1
echo 3 >/proc/sys/vm/drop_caches
sleep 1
dosfsck -aw /dev/mmcblk0p1
mount -t vfat -o noatime -o nodiratime -o shortname=mixed  /dev/mmcblk0p1 /mnt/sd1
echo "mount sd "